name: Android CI

on:
  push:
    branches: [ "dagger_assisted_factory_bug" ]
  pull_request:
    branches: [ "dagger_assisted_factory_bug" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Execute Reproducer
        run: |
          chmod +x bug.sh
          ./bug.sh
